#include "yk/scene/RegistryDocs.hpp"
#include <algorithm>
#include <map>
#include <sstream>

namespace yk {
namespace {
const char *typeName(PropertyType type) {
    switch (type) {
    case PropertyType::Bool:
        return "bool";
    case PropertyType::Int:
        return "int";
    case PropertyType::Float:
        return "float";
    case PropertyType::String:
        return "string";
    case PropertyType::Vec2:
        return "vec2";
    case PropertyType::Color:
        return "color";
    case PropertyType::Enum:
        return "enum";
    case PropertyType::EntityReference:
        return "entity";
    case PropertyType::EntityReferenceList:
        return "entity list";
    case PropertyType::StringList:
        return "string list";
    case PropertyType::Asset:
        return "asset";
    }
    return "?";
}
std::string valueText(const PropertyInfo &property) {
    const PropertyValue &value = property.defaultValue;
    switch (property.type) {
    case PropertyType::Bool:
        return std::get<bool>(value) ? "true" : "false";
    case PropertyType::Int:
        return std::to_string(std::get<std::int64_t>(value));
    case PropertyType::Float:
    case PropertyType::Vec2:
    case PropertyType::Color:
    case PropertyType::String:
    case PropertyType::Enum:
    case PropertyType::Asset:
    case PropertyType::EntityReference:
    case PropertyType::EntityReferenceList:
    case PropertyType::StringList: {
        const std::string text = propertyToJson(property, value).dump();
        return text == "null" ? "none" : text;
    }
    }
    return {};
}
std::string escapeCell(std::string text) {
    for (std::size_t at = 0; (at = text.find('|', at)) != std::string::npos; at += 2)
        text.replace(at, 1, "\\|");
    return text;
}
} // namespace

std::string describeRegistryMarkdown(const ComponentRegistry &registry) {
    std::ostringstream out;
    out << "# Component reference\n\n"
           "Generated by `yk_player --components` from the same reflection data the editor's "
           "inspector uses.\n"
           "Do not edit by hand; a test fails when this file is stale.\n";
    std::map<std::string, std::vector<const ComponentType *>> byCategory;
    for (const auto &type : registry.types())
        byCategory[type->category].push_back(type.get());
    for (auto &[category, types] : byCategory) {
        out << "\n## " << category << "\n";
        for (const ComponentType *type : types) {
            out << "\n### " << type->name << "\n\n";
            if (!type->description.empty())
                out << type->description << "\n\n";
            if (!type->dependencies.empty()) {
                out << "Requires:";
                for (const std::string &dependency : type->dependencies)
                    out << " `" << dependency << "`";
                out << "\n\n";
            }
            if (type->allowMultiple)
                out << "Several instances may be added to one entity.\n\n";
            out << "| Property | Type | Default | Notes |\n|---|---|---|---|\n";
            for (const PropertyInfo &property : type->properties) {
                std::string notes = property.tooltip;
                if (property.hasRange) {
                    std::ostringstream range;
                    range << "range " << property.minValue << " to " << property.maxValue;
                    notes += (notes.empty() ? "" : " ") + std::string("(") + range.str() + ")";
                }
                if (property.type == PropertyType::Enum && property.options.size() <= 12) {
                    notes += (notes.empty() ? "" : " ") + std::string("Options:");
                    for (const std::string &option : property.options)
                        notes += " " + option;
                }
                if (property.readOnly)
                    notes += (notes.empty() ? "" : " ") + std::string("(runtime state, not saved)");
                out << "| `" << property.name << "` | " << typeName(property.type) << " | "
                    << escapeCell(valueText(property)) << " | " << escapeCell(notes) << " |\n";
            }
        }
    }
    out << "\n## Entity templates\n\nOffered by the editor's Create menu.\n";
    std::map<std::string, std::vector<std::string>> templates;
    for (const EntityTemplate &entry : registry.templates())
        templates[entry.category].push_back(entry.name);
    for (const auto &[category, names] : templates) {
        out << "\n- **" << category << "**:";
        for (const std::string &name : names)
            out << " " << name << ";";
        out << "\n";
    }
    return out.str();
}
} // namespace yk
