"""Writes editor/ui/Codicons.hpp: the UTF-8 strings of the Codicons glyphs the editor draws.

    python3 gen_codicons.py fonts/codicon.csv ../ui/Codicons.hpp

Edit ICONS to add one (names are in codicon.csv), rerun, commit the header. The font itself
(fonts/codicon.ttf, Codicons by Microsoft, CC-BY-4.0, see LICENSES/) is embedded by CMake.
"""
import csv
import sys

ICONS = """
files list-tree package extensions rocket settings-gear search
layout-sidebar-left layout-sidebar-left-off layout-panel layout-panel-off layout-sidebar-right layout-sidebar-right-off
debug-start debug-pause debug-step-over debug-stop debug-restart run-all
move expand-all refresh magnet symbol-ruler zoom-in zoom-out screen-full
layers eye eye-closed lock unlock link link-external
file-text folder folder-opened file-media unmute file-code file-binary edit trash copy clippy add close
chevron-right chevron-down chevron-up kebab-vertical ellipsis
warning error info check circle-filled circle-large-filled save save-all discard redo filter new-file new-folder
go-to-file output terminal bug graph pulse dashboard debug-console list-unordered root-folder tag symbol-class
symbol-method symbol-property symbol-event symbol-color symbol-namespace symbol-structure symbol-misc symbol-variable
home window target cursor type-hierarchy split-horizontal split-vertical pin book gear tools beaker checklist
arrow-up arrow-down arrow-left arrow-right triangle-right triangle-down dash remove circle question lightbulb
mirror flame star-full sparkle wand editor-layout gripper grabber play circle-small-filled record symbol-file
""".split()


def main(csv_path, out_path):
    rows = list(csv.DictReader(open(csv_path, encoding="utf-8-sig")))
    codes = {r["short_name"]: int(r["unicode"], 16) for r in rows}
    missing = [n for n in ICONS if n not in codes]
    if missing:
        sys.exit("unknown codicons: " + ", ".join(missing))
    lines = ["// Generated by editor/resources/gen_codicons.py from Codicons (Microsoft, CC-BY-4.0). Do not edit.",
             "#pragma once", "", "// clang-format off", "namespace yk::editor::ui::codicon {"]
    seen = set()
    for name in ICONS:
        if name in seen:
            continue
        seen.add(name)
        ident = "".join(part.capitalize() if i else part for i, part in enumerate(name.split("-")))
        code = codes[name]
        utf8 = chr(code).encode("utf-8")
        escaped = "".join("\\x%02x" % b for b in utf8)
        lines.append('inline constexpr const char *%s = "%s"; // U+%04X' % (ident, escaped, code))
    lines.append("} // namespace yk::editor::ui::codicon")
    lines.append("// clang-format on")
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
