# Embeds binary files (fonts) into a C++ source file as byte arrays, at configure time, so the
# editor is a single executable with nothing to find at run time.
#
#   yk_embed_files(<output.cpp> NAMESPACE <ns> FILES <symbol>=<path> ...)
#
# writes `const unsigned char <symbol>[]` and `const std::size_t <symbol>Size` into <ns>. The output
# is regenerated when any input changes.
function(yk_embed_files output)
    cmake_parse_arguments(ARG "" "NAMESPACE" "FILES" ${ARGN})
    set(text "// Generated by cmake/YkEmbed.cmake. Do not edit.\n#include <cstddef>\nnamespace ${ARG_NAMESPACE} {\n")
    foreach(item ${ARG_FILES})
        string(REPLACE "=" ";" parts "${item}")
        list(GET parts 0 symbol)
        list(GET parts 1 path)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")
        file(READ "${path}" hex HEX)
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
        string(APPEND text "extern const unsigned char ${symbol}[];\nextern const std::size_t ${symbol}Size;\n")
        string(APPEND text "const unsigned char ${symbol}[] = {${bytes}};\nconst std::size_t ${symbol}Size = sizeof ${symbol};\n")
    endforeach()
    string(APPEND text "} // namespace ${ARG_NAMESPACE}\n")
    file(WRITE "${output}.tmp" "${text}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${output}.tmp" "${output}")
    file(REMOVE "${output}.tmp")
endfunction()
