# Builds copies of the YK programs for a game that has components of its own.
#
# The stock yk_player, yk_editor and yk know the engine's components and the gameplay library. A
# game whose rules need C++ (see docs/BUILDING.md, "Game modules") puts its components in a library
# and lets this function build the three programs with them registered:
#
#   add_subdirectory(YK-Engine)                  # or FetchContent: the engine is an ordinary subdirectory
#   include(YkGame)                              # (YK-Engine's cmake/ is on CMAKE_MODULE_PATH)
#   add_library(my_game_module STATIC src/MyGame.cpp)
#   target_link_libraries(my_game_module PUBLIC yk::gameplay)
#   yk_add_game_hosts(my_game MODULE my_game_module HEADER MyGame.hpp REGISTER my_game::registerComponents)
#
# creates my_game_player, my_game_editor (when the engine builds the editor) and my_game_tool (the
# `yk` command line). REGISTER names a function `void f(yk::ComponentRegistry &)` declared in HEADER.
# The programs behave exactly like the stock ones (same options, same project files) and export the
# same way: pass the game's player to `yk export --player` or the Export dialog.
function(yk_add_game_hosts name)
    cmake_parse_arguments(ARG "" "MODULE;HEADER;REGISTER" "" ${ARGN})
    if(NOT ARG_MODULE OR NOT ARG_HEADER OR NOT ARG_REGISTER)
        message(FATAL_ERROR "yk_add_game_hosts(${name}) needs MODULE, HEADER and REGISTER")
    endif()
    set(generated "${CMAKE_CURRENT_BINARY_DIR}/yk-game-hosts/${name}")
    set(programs tool)
    if(TARGET yk_player_host)
        list(APPEND programs player)
    endif()
    if(TARGET yk_editor_host)
        list(APPEND programs editor)
    endif()
    foreach(program ${programs})
        set(function runTool)
        if(program STREQUAL "player")
            set(function runPlayer)
        elseif(program STREQUAL "editor")
            set(function runEditor)
        endif()
        # Only rewritten when the content changes, so a reconfigure does not rebuild the program.
        file(CONFIGURE OUTPUT "${generated}/${program}_main.cpp" @ONLY CONTENT
"// Generated by yk_add_game_hosts(${name}): the stock ${program} with ${ARG_REGISTER} registered.
#include \"yk/host/Hosts.hpp\"
#include \"${ARG_HEADER}\"

int main(int argc, char **argv) {
    return yk::host::${function}(argc, argv, ${ARG_REGISTER});
}
")
        add_executable(${name}_${program} "${generated}/${program}_main.cpp")
        target_link_libraries(${name}_${program} PRIVATE yk_${program}_host ${ARG_MODULE})
    endforeach()
endfunction()
