# Shared target helpers: warnings-as-errors and optional sanitizers for project code.
function(yk_sanitize target)
    if(NOT YK_SANITIZERS)
        return()
    endif()
    if(MSVC)
        target_compile_options(${target} PRIVATE /fsanitize=address /Zi)
        target_link_options(${target} PUBLIC /INCREMENTAL:NO)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        target_compile_options(${target} PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
        target_link_options(${target} PUBLIC -fsanitize=address,undefined)
    else()
        message(FATAL_ERROR "YK_SANITIZERS requires MSVC, Clang or GCC")
    endif()
endfunction()

function(yk_target target)
    target_compile_features(${target} PUBLIC cxx_std_20)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4 /WX /permissive- /EHsc)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow -Werror)
    endif()
    yk_sanitize(${target})
endfunction()

# Executable test with the repository's conventions (strict warnings, timeout, CTest entry).
function(yk_add_test name source)
    cmake_parse_arguments(ARG "" "TIMEOUT" "LIBS;ENVIRONMENT;DEFINITIONS" ${ARGN})
    add_executable(yk_${name}_tests ${source})
    target_link_libraries(yk_${name}_tests PRIVATE ${ARG_LIBS})
    target_include_directories(yk_${name}_tests PRIVATE "${PROJECT_SOURCE_DIR}/tests")
    if(ARG_DEFINITIONS)
        target_compile_definitions(yk_${name}_tests PRIVATE ${ARG_DEFINITIONS})
    endif()
    yk_target(yk_${name}_tests)
    add_test(NAME ${name} COMMAND yk_${name}_tests)
    if(NOT ARG_TIMEOUT)
        set(ARG_TIMEOUT 60)
    endif()
    set_tests_properties(${name} PROPERTIES TIMEOUT ${ARG_TIMEOUT})
    if(ARG_ENVIRONMENT)
        set_tests_properties(${name} PROPERTIES ENVIRONMENT "${ARG_ENVIRONMENT}")
    endif()
endfunction()
