"""Drawing helpers shared by the art generators.

Everything is drawn at SS times the final resolution and scaled down with a high quality filter,
which gives smooth, anti-aliased shapes with no external art tools. All art in this project is
generated by these scripts: it is original placeholder art (no third-party assets).
"""
import math
import random

import numpy as np
from PIL import Image, ImageChops, ImageDraw, ImageFilter

SS = 4  # supersampling factor


def rgba(color, alpha=255):
    """'#rrggbb' or (r, g, b[, a]) -> (r, g, b, a)."""
    if isinstance(color, str):
        color = color.lstrip("#")
        r, g, b = int(color[0:2], 16), int(color[2:4], 16), int(color[4:6], 16)
        a = int(color[6:8], 16) if len(color) >= 8 else alpha
        return (r, g, b, a)
    if len(color) == 3:
        return (color[0], color[1], color[2], alpha)
    return tuple(color)


def mix(a, b, t):
    a, b = rgba(a), rgba(b)
    return tuple(int(round(a[i] + (b[i] - a[i]) * t)) for i in range(4))


def shade(color, factor):
    """Multiply the brightness of a color (factor < 1 darkens, > 1 lightens toward white)."""
    r, g, b, a = rgba(color)
    if factor <= 1:
        return (int(r * factor), int(g * factor), int(b * factor), a)
    t = factor - 1
    return (int(r + (255 - r) * t), int(g + (255 - g) * t), int(b + (255 - b) * t), a)


class Canvas:
    """A transparent RGBA canvas of w x h final pixels, drawn at SS x resolution."""

    def __init__(self, w, h, ss=SS):
        self.w, self.h, self.ss = w, h, ss
        self.img = Image.new("RGBA", (w * ss, h * ss), (0, 0, 0, 0))

    # ---- coordinate helpers (all inputs in final pixels, floats allowed) ----
    def _p(self, pts):
        return [(x * self.ss, y * self.ss) for x, y in pts]

    def layer(self):
        """A new transparent layer of the same size; draw on it, then composite()."""
        return Layer(self)

    def composite(self, layer):
        self.img = Image.alpha_composite(self.img, layer.img)

    # ---- direct drawing (onto the canvas itself) ----
    def ellipse(self, cx, cy, rx, ry, fill, outline=None, width=0):
        d = ImageDraw.Draw(self.img)
        box = [(cx - rx) * self.ss, (cy - ry) * self.ss, (cx + rx) * self.ss, (cy + ry) * self.ss]
        d.ellipse(box, fill=rgba(fill) if fill else None,
                  outline=rgba(outline) if outline else None, width=int(width * self.ss))

    def polygon(self, pts, fill, outline=None, width=0):
        d = ImageDraw.Draw(self.img)
        d.polygon(self._p(pts), fill=rgba(fill) if fill else None)
        if outline:
            d.line(self._p(list(pts) + [pts[0]]), fill=rgba(outline), width=int(width * self.ss), joint="curve")

    def rrect(self, x0, y0, x1, y1, r, fill, outline=None, width=0):
        d = ImageDraw.Draw(self.img)
        d.rounded_rectangle([x0 * self.ss, y0 * self.ss, x1 * self.ss, y1 * self.ss], radius=r * self.ss,
                            fill=rgba(fill) if fill else None,
                            outline=rgba(outline) if outline else None, width=int(width * self.ss))

    def rect(self, x0, y0, x1, y1, fill):
        d = ImageDraw.Draw(self.img)
        d.rectangle([x0 * self.ss, y0 * self.ss, x1 * self.ss - 1, y1 * self.ss - 1], fill=rgba(fill))

    def line(self, pts, fill, width=1.0):
        d = ImageDraw.Draw(self.img)
        d.line(self._p(pts), fill=rgba(fill), width=max(1, int(width * self.ss)), joint="curve")

    def arc(self, cx, cy, rx, ry, start, end, fill, width=1.0):
        d = ImageDraw.Draw(self.img)
        box = [(cx - rx) * self.ss, (cy - ry) * self.ss, (cx + rx) * self.ss, (cy + ry) * self.ss]
        d.arc(box, start, end, fill=rgba(fill), width=max(1, int(width * self.ss)))

    def paste(self, image, x, y):
        """Alpha-composite a final-resolution RGBA image at (x, y) final pixels."""
        big = image.resize((image.width * self.ss, image.height * self.ss), Image.NEAREST)
        base = Image.new("RGBA", self.img.size, (0, 0, 0, 0))
        base.paste(big, (int(x * self.ss), int(y * self.ss)))
        self.img = Image.alpha_composite(self.img, base)

    def result(self):
        return self.img.resize((self.w, self.h), Image.LANCZOS)


class Layer(Canvas):
    def __init__(self, parent):
        self.w, self.h, self.ss = parent.w, parent.h, parent.ss
        self.img = Image.new("RGBA", parent.img.size, (0, 0, 0, 0))

    def mask(self):
        return self.img.getchannel("A")


def gradient_v(w, h, top, bottom):
    """A vertical gradient image (w x h)."""
    top, bottom = np.array(rgba(top), float), np.array(rgba(bottom), float)
    t = np.linspace(0, 1, h)[:, None, None]
    arr = top * (1 - t) + bottom * t
    arr = np.broadcast_to(arr, (h, w, 4)).astype(np.uint8)
    return Image.fromarray(arr, "RGBA")


def gradient_radial(w, h, center, edge, cx=0.5, cy=0.5, radius=0.5):
    """A radial gradient from `center` color at (cx, cy) to `edge` at the given radius (fractions)."""
    ys, xs = np.mgrid[0:h, 0:w]
    d = np.sqrt(((xs / w - cx) / radius) ** 2 + ((ys / h - cy) / radius) ** 2)
    t = np.clip(d, 0, 1)[:, :, None]
    c, e = np.array(rgba(center), float), np.array(rgba(edge), float)
    return Image.fromarray((c * (1 - t) + e * t).astype(np.uint8), "RGBA")


def fill_masked(size, mask, image):
    """Returns `image` (same size as `size`) visible only where `mask` (L image) is set."""
    out = Image.new("RGBA", size, (0, 0, 0, 0))
    out.paste(image, (0, 0), mask)
    return out


def blur(image, radius):
    return image.filter(ImageFilter.GaussianBlur(radius))


def add_alpha_noise(image, amount, seed=1):
    """Modulate brightness by tileable-ish noise (keeps alpha)."""
    rng = np.random.default_rng(seed)
    arr = np.array(image).astype(float)
    noise = rng.normal(0, amount, arr.shape[:2])[:, :, None]
    arr[:, :, :3] = np.clip(arr[:, :, :3] + noise, 0, 255)
    return Image.fromarray(arr.astype(np.uint8), "RGBA")


def sheet(frames, columns, cell_w, cell_h):
    """Lays out frame images in a grid (row major) and returns the sheet image + rows."""
    rows = (len(frames) + columns - 1) // columns
    out = Image.new("RGBA", (columns * cell_w, rows * cell_h), (0, 0, 0, 0))
    for i, frame in enumerate(frames):
        out.paste(frame, ((i % columns) * cell_w, (i // columns) * cell_h))
    return out, rows


def save(image, path):
    import os
    os.makedirs(os.path.dirname(path), exist_ok=True)
    image.save(path, optimize=True)


def write_json(path, doc):
    import json
    import os
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(doc, f, indent=2)
        f.write("\n")


def anim_doc(texture, columns, rows, clips):
    return {"format": "yk.animation", "version": 2, "texture": texture, "columns": columns, "rows": rows,
            "clips": clips}


def controller_doc(parameters, entry, states, transitions):
    return {"format": "yk.animator", "version": 1, "parameters": parameters, "entry": entry, "states": states,
            "transitions": transitions}


def write_texture_meta(path, meta):
    doc = {"format": "yk.texture", "version": 1}
    doc.update(meta)
    write_json(path + ".ykmeta", doc)
